### ISSUE TITLE
Add Oscam emu?

### ISSUE THREAD

**Issue by lorba7068** [oscam-emu/oscam-patched#102]
Is it possible to add this arrangement? I notice that some have a patch to fix this problem, PV emu has become private...
![7986066765](https://user-images.githubusercontent.com/44327561/226947747-62fcd366-73de-40c2-ac1b-8724f644ace4.jpg)
![850707373](https://user-images.githubusercontent.com/44327561/226947763-ab78b1db-7450-4f79-b148-7a7c4a6741de.jpg)
![780970345](https://user-images.githubusercontent.com/44327561/226947773-423aeef1-8d80-49ea-beef-735963d74909.jpg)
![430971186](https://user-images.githubusercontent.com/44327561/226947786-7effbf09-3821-4ff3-aa31-95265c0f481d.jpg)

**Comment by WXbet** [comment]
Should work with oscam-emu 800.

**Comment by lorba7068** [comment]
emu 800 does not seem to solve the problem, despite having emmkey and keys 00 and 01 valid.
[log.txt](https://github.com/oscam-emu/oscam-patched/files/14643123/log.txt)
![Snap1](https://github.com/oscam-emu/oscam-patched/assets/44327561/d8742cc6-5ff1-4781-be77-ab0b07f000c3)
![Snap2](https://github.com/oscam-emu/oscam-patched/assets/44327561/2e2d20bc-bfb0-41ff-bed9-9abbc7b79b26)

**Comment by EnoSat** [comment]
> emu 800 does not seem to solve the problem, despite having emmkey and keys 00 and 01 valid.
emu 800 does not support nano01
