### ISSUE TITLE
Icam DE patch

### ISSUE THREAD

**Issue by AbuBaniaz** [oscam-emu/oscam-patched#103]
Is it possible to incorporate the Icam patch. A DE version is available on link below. Hopefully those with the IT/UK one will make it available.

https://raw.githubusercontent.com/OpenPLi/openpli-oe-core/develop/meta-openpli/recipes-openpli/enigma2-softcams/enigma2-plugin-softcams-oscam-emu/icam.patch

**Comment by oscam-emu** [comment]
@AbuBaniaz can you contact me at the email listed in my profile?

**Comment by AbuBaniaz** [comment]
I responded yesterday. Please check spam folder.

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/oscam-emu/oscam-patched/commit/997b30bbb597cb4e7bc7dbe6ce8e34a17f85e914

Many thanks
