### ISSUE TITLE
director.c warning

### ISSUE THREAD

**Issue by yogofogo11** [oscam-emu/oscam-patched#105]
May I ask you to fix the warning in director.c module.

`CC	module-emulator-cryptoworks.c
CC	module-emulator-.c
module-emulator-director.c: In function 'parse_emm_nano_tags':
module-emulator-director.c:484:75: warning: the comparison will always evaluate as 'true' for the pointer operand in 'tagData + 16' must not be NULL [-Waddress]
  484 |                                                 if ((tagData + 4 + 5 + 7) != 0x00) // check if key looks valid (last byte 0x00)
      |                                                                           ^~
CC	module-emulator-irdeto.c
CC	module-emulator-nagravision.c
`

Thanks,
BR

**Comment by WXbet** [comment]
Fixed in oscam-emu 800.
