### ISSUE TITLE
Support for PowerVu modeCW 4

### ISSUE THREAD

**Issue by jlmariense** [oscam-emu/oscam-patched#11]
Hello friends, just the mux globosat of 65W and 75W satellites, coded. Below the oscam log:
2018/07/02 17:34:40 04D832E1 r      (emu) ecm1:803045503F200E0078089276262863E95F5F00EAB00077734C0CF5DA9DE4F40DE367039C2808400000CD5B493858159C8E1C6F7441B7EEA451411FAE212058CC527E3BDB893B29B4
2018/07/02 17:34:40 04D832E1 r      (emu) csaUsed=0,xorMode=0,ecmSrvid=132,hashModeCw=1,modeCW=4

**Comment by luizaum2** [comment]
please add in the Oscam emulator the new hash mode in use 30.
65/75 / 84w satellites

2019/02/21 22:07:22 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:61C73FFB68BEDB1AD43DE3B486A43BBA): found (2 ms) by emulator - Globonews HD
2019/02/21 22:07:23 2B663645 r (emu) A new hash mode [30] is in use.
2019/02/21 22:07:23 43E67A02 c (-) -- Skipped 7 duplicated log lines --
2019/02/21 22:07:23 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:AF3292F1DC313FAD826184D590889045): found (2 ms) by emulator - Globonews HD
2019/02/21 22:07:24 2B663645 r (emu) A new hash mode [30] is in use.
2019/02/21 22:07:24 43E67A02 c (-) -- Skipped 7 duplicated log lines --
2019/02/21 22:07:24 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:3B3079847196AF761F1CA7C80AC3748F): found (2 ms) by emulator - Globonews HD
2019/02/21 22:07:25 2B663645 r (emu) A new hash mode [30] is in use.
2019/02/21 22:07:25 43E67A02 c (-) -- Skipped 7 duplicated log lines --
2019/02/21 22:07:25 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:042BC4EDD00B20BFB06AE1C9010881A3): found (3 ms) by emulator - Globonews HD
2019/02/21 22:07:26 2B663645 r (emu) A new hash mode [30] is in use.
2019/02/21 22:07:26 43E67A02 c (-) -- Skipped 7 duplicated log lines --
2019/02/21 22:07:26 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:35D34EB28052859C0BFF39C56F9668FA): found (4 ms) by emulator - Globonews HD
2019/02/21 22:07:27 2B663645 r (emu) A new hash mode [30] is in use.
2019/02/21 22:07:27 43E67A02 c (-) -- Skipped 7 duplicated log lines --
2019/02/21 22:07:27 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:CC7ACFF3C26DD9F32769F996C8639C78): found (3 ms) by emulator - Globonews HD
2019/02/21 22:07:28 2B663645 r (emu) A new hash mode [30] is in use.
2019/02/21 22:07:28 43E67A02 c (-) -- Skipped 7 duplicated log lines --
2019/02/21 22:07:28 43E67A02 c (ecm) dvbapi (0E00@000000/0000/00A9/48:4DAEBE4144025D471E0A50920F8D90FB): found (3 ms) by emulator - Globonews HD
