### ISSUE TITLE
only 2 powervu channels are decrypted at once without streamrelay

### ISSUE THREAD

**Issue by PeterMaxu** [oscam-emu/oscam-patched#12]
only 2 powervu channels are decrypted at once without streamrelay and vti image.

**Comment by oscam-emu** [comment]
This is not actually an issue. It is a hardware limitation of your box (and any box).

Every box has a total number of hardware descramblers that can be used, usually 8. Each scrambled (crypted) stream in each channel takes up one descrambler. So, if you are watching or recording 3 channels with 1 video and 2 audio stream each one, then you need a total of 9 descramblers. Which might be over your box's capabilities.

You can limit the number of scrambled streams that are used per channel with the "Max pids for extended CWs" option, under the dvb-api config. But maybe you will loose some useful (audio) streams, or maybe not.

On the other hand, the stream relay is using the cpu for descrambling, thus it does not have such restrictions.
