### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by tromoto** [oscam-emu/oscam-patched#120]
config.sh has attr 664 instead of 755 ---> cmake fails

**Comment by nautilus7** [comment]
Yes, that was done with upstream oscam 11754...

**Comment by WXbet** [comment]
Maybe this was my fault during merge 😑

**Comment by nautilus7** [comment]
https://stackoverflow.com/questions/10516201/updating-and-committing-only-a-files-permissions-using-git-version-control

I have done the same mistake before and took me a few hours to figure out how to fix it.

**Comment by nautilus7** [comment]
Later, not now. But no problem, everyone can wait.

**Comment by AbuBaniaz** [comment]
https://github.com/oscam-emu/oscam-patched/commit/75676529bd40c70c592ae0649c23f8f8890f9a8d 

Another guide
http://blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html

**Comment by nautilus7** [comment]
It also needs to be fixed in the trunk I think.

**Comment by nautilus7** [comment]
No, I mean the streamboard svn repository. I think the changes there is the source of this problem.

**Comment by AbuBaniaz** [comment]
> You mean the oscam-svn branch of this same repo?

Checked, that is fine
```100755 blob 07026a96c1f28de5a5e01a4d8f359a4ee4332f49    config.sh
```
So is this
https://github.com/oscam-emu/oscam-svn/tree/trunk

I think it was an accidental/windows error

**Comment by WXbet** [comment]
No, trunk dhould be okay. The problem occured during merge the the changes to oscam-patched. This was done on Windows by me. And git on Windows seems respect the file permissions by default. I fogot to explicit switch the file to 755. I can change it, but not before tonight.

**Comment by AbuBaniaz** [comment]
It's fixed.  I'll close the issue now.

**Comment by nautilus7** [comment]
Yes, all good now in every repo.

**Comment by WXbet** [comment]
I will re-apply the merge from trunk tonight incl. correct file permissions. So we don’t have this seperate commit.

**Comment by nautilus7** [comment]
Don't bother, not worth the trouble. Let alone more commits are already done.

I am also thinking protecting the master branch from force commits, since now there are more people working on the repo.
So, it can only create difficulties.
