### ISSUE TITLE
Possible to add modeCW 1 enhancement?

### ISSUE THREAD

**Issue by yogofogo11** [oscam-emu/oscam-patched#125]
May I ask, if it would be possible to add the modeCW 1 in the PV module?

(emu) csaUsed: 0, xorMode: 0, ecmSrvid: 006D (109), hashModeCw: 1, modeCW: 1

**Comment by WXbet** [comment]
Do you have more information about this? Maybe you have a code snippet or patch we can investigate…

**Comment by yogofogo11** [comment]
Unfortunately I don't have one. Therefore I asked.
(emu) channel hash: 898BB43A, group id: 48E1

**Comment by bracarino** [comment]
> Do you have more information about this? Maybe you have a code snippet or patch we can investigate…

I can provide with full stream and valid keys. Does that work?

**Comment by nautilus7** [comment]
No. Feel free to send us the code...
