### ISSUE TITLE
Possible to add PowerVu ECM nano 01?

### ISSUE THREAD

**Issue by bracarino** [oscam-emu/oscam-patched#127]
Hello, 

Is it possible to include ECM "nano 01" feature in PowerVu?
This happens in some transponders in 58, 55 and 40W.

Oscam seems to decrypt correctly (with proper ECM heys), as no error is shown on logs. But, no image/sound is shown.

Thank you

**Comment by nautilus7** [comment]
Feel free to send us the code...
