### ISSUE TITLE
Missing config.sh --emu-version

### ISSUE THREAD

**Issue by WXbet** [oscam-emu/oscam-patched#16]
Hi @nautilus7: This lines are not present in the "new" oscam-patched: https://github.com/oscam-emu/oscam-patched-old/blob/master/config.sh#L727-L729

Is this correct or was it lost during transition?

**Comment by nautilus7** [comment]
Removed thme on purpose. Do you need them back?

**Comment by WXbet** [comment]
s3 uses this currently, but I can change it, no problem. No need from my side.
