### ISSUE TITLE
Hash mode cw 23 

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-patched#17]
Measat Packages @ 91.4°E

Hash mode cw 23
Powervu  need fix oscam emu

**Comment by oscam-emu** [comment]
Fixed with commit https://github.com/oscam-emu/oscam-patched/commit/1a3721e2c36cd0a2e3676f5992c5de961c2c4e7f and included in emu 778.
Next time post your request in the already opened issue #15. No need to open a new  issue for each new hash mode. Thanks for understanding.
