### ISSUE TITLE
[makefile] Fixed linking of empty SoftCam.Key file on aarch64 boxes

### ISSUE THREAD

**Issue by sattotal** [oscam-emu/oscam-patched#20]
patch doesn't work on Cygwin based compilations
with patch I got below errors:

> ld: unknown option »-z« ld: please useoption --help for information
> objcopy: 'SoftCam.Key.o': No such file

**Comment by oscam-emu** [comment]
Please test with latest commit.

**Comment by sattotal** [comment]
Thanks for fast answer but the problem still exists because ld doesn't support the option -z  in the Makefile

**Comment by oscam-emu** [comment]
Can't you upgrade/update to a version that supports the -z option?

https://stackoverflow.com/questions/29178445/what-is-the-z-option-for-in-this-gcc-compiler-command

**Comment by sattotal** [comment]
for Cygwin I have updated to GNU ld (GNU Binutils) 2.31.1 (latest version) .
However there is no -z Option available
without "-z noexecstack" I can build without error

**Comment by sattotal** [comment]
a possible workaround is using
#if defined(__CYGWIN__)
..
#else 

#endif

**Comment by oscam-emu** [comment]
thanks will look into it, when I finished some other things I do.

**Comment by oscam-emu** [comment]
The linking method was reverted to the old one, so everything should be back to normal.

A new config option WITH_SOFTCAM is introduced that allows linking or not of the SoftCam.Key file during compilation.

**Comment by sattotal** [comment]
#2078 [osemu] New config option to control SoftCam.Key linking in binary 
Thanks for this well working fix ;)
