### ISSUE TITLE
No video/sound on PowerVU ch in TVHeadend

### ISSUE THREAD

**Issue by Shporterator** [oscam-emu/oscam-patched#23]
Hi. I use TVHeadend and Oscam
After upgrading to r11451-784, PowerVU channels do not have images or do not open at all.
Version OSCam: 1.20-unstable_svn Build: r11424 everything is fine.

**Comment by oscam-emu** [comment]
Did change your config according to https://github.com/oscam-emu/oscam-patched/wiki/PowerVU-config#november-2018-update---attention

**Comment by Shporterator** [comment]
Now it works. Thanks.
