### ISSUE TITLE
constant CW file and constcw protocol problems!!!

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-patched#26]
**hi,
oscam says " we have got reader and it can be read biss keys in constantcw file and **[protocol](http://www.streamboard.tv/wiki/OSCam/en/Config/oscam.server#protocol)** name is [constcw](http://www.streamboard.tv/wiki/OSCam/en/examples/Reader#Constant_CW) " but they are protocol i think dont work with home sharing / biss sharing..

i did try constant.cw file sharing with hd mini receiver but channels dont open

normal emulator can open channels hd mini receiver

i dont never try local sat tuner in biss channels . for example, dm800 and oscam with biss channels,

oscam cant do it

can you help ?
regards**

**Comment by PAKO34** [comment]
### **hola budiarno? how to understand this?**

**Comment by oscam-emu** [comment]
@PAKO34, I don't understand what you're writing and what you're trying to do...

Emu only supports BISS, not constant cw. There is a dedicated module for constant cw in oscam.

**Comment by oscam-emu** [comment]
Please don't spam...
