### ISSUE TITLE
ver 788 make fail

### ISSUE THREAD

**Issue by mihaip1948** [oscam-emu/oscam-patched#29]
the last patches for ver 788 introduces a linker
failure "segmentation fault" using Aarch64 compiler
building Oscam without EMU all is OK !

**Comment by oscam-emu** [comment]
Use gcc 8.2.0 or build with `./config.sh --disable WITH_SOFTCAM`.

**Comment by mihaip1948** [comment]
Thanks but ... sollution does not work !!!
- Aarch64 dows not have gcc 8.2.0 
- and disable WIT_SOFTCAM cause tens of warnings an finnaly an abort !!!

**Comment by oscam-emu** [comment]
1. You an use a custom toolchain, e.g. from https://toolchains.bootlin.com/

2. That's not the case on my system. Compilation works perfectly fine here. Post your logs.

**Comment by mihaip1948** [comment]
thanks ! I have 7.3 !!!
