### ISSUE TITLE
Be out Q how to work? 

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-patched#31]
**Be out Q how to work? we have keys but it doesnt work?

they are h.265**  what do you think?

**Comment by PAKO34** [comment]
**i asked you before but you dont explain and closed my old topic?**

**Comment by oscam-emu** [comment]
So, you ask again? If there is some progress regarding I'll let you know.

**Comment by PAKO34** [comment]
**i hope..**
