### ISSUE TITLE
RSA KEYS ABOUT?

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-patched#34]
**Are you add in emu rsa keys? for example **
**second questions? mgcamd autoroll.key file out of for oscam emu?
thank you**

**Comment by oscam-emu** [comment]
WTF? What is this nonsense? Why do you post keys publicly?

What exactly is your question? What should we do with these keys anyway?

**Comment by PAKO34** [comment]
**mgcamd using autoroll.key file

is oscam emu use autoroll.key file?**

**Comment by oscam-emu** [comment]
oscam-emu operates differently than mgcamd.
