### ISSUE TITLE
Link error trying to build static-libcrypto

### ISSUE THREAD

**Issue by mihaip1948** [oscam-emu/oscam-patched#46]
make -j 6 CONF_DIR=/plugin/var/tuxbox/config USE_UTF8=1  CROSS=/home/mihaip/oscam-ndk/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24- USE_LIBCRYPTO=1 LIB_RT= LIB_PTHREAD= CC="armv7a-linux-androideabi24-clang -Wno-invalid-command-line-argument" STRIP=arm-linux-androideabi-strip LIBCRYPTO_LIB="/home/mihaip/oscam-ndk/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/libcrypto.a"

**Comment by mihaip1948** [comment]
Normal link with shared libcrypto is working ! but build with static libraries fail 
due to multiple definitions  in oscam-biss 

INK	Distribution/oscam-1.20_svn11518-796-armv7a-unknown-linux-android24.debug
/home/mihaip/oscam-ndk/oscam-svn/../android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/mihaip/oscam-ndk/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/libcrypto.a(des_enc.o): multiple definition of 'DES_SPtrans'
/home/mihaip/oscam-ndk/oscam-svn/../android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: build/armv7a-unknown-linux-android24/cscrypt/mdc2.o: previous definition here
/home/mihaip/oscam-ndk/oscam-svn/../android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/mihaip/oscam-ndk/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/libcrypto.a(des_enc.o): multiple definition of 'DES_encrypt1'
/home/mihaip/oscam-ndk/oscam-svn/../android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: build/armv7a-unknown-linux-android24/cscrypt/mdc2.o: previous definition here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:435: recipe for target 'Distribution/oscam-1.20_svn11518-796-armv7a-unknown-linux-android24.debug' failed
make[1]: *** [Distribution/oscam-1.20_svn11518-796-armv7a-unknown-linux-android24.debug] Error 1

**Comment by oscam-emu** [comment]
I am aware of this. The problem is that the/cscrypt/mdc2.c file, which contains code taken from libcrypto itself (thus common function names)  is built anyway, despite using libcrypto.

I sent [a fix for this in oscam](http://www.streamboard.tv/oscam/changeset/11512/trunk), but they reverted it because it broke the native x64 build in debian/ubuntu, as the openssl/libcrypto pre-built package that comes with these distros does not contain the mdc2 algorithm. 

And after that, I didn't try anything different to solve this problem.

**Comment by mihaip1948** [comment]
Ok tahanks !
