### ISSUE TITLE
ERROR: 'emu' is unsupported reader protocol!

### ISSUE THREAD

**Issue by limiteddi** [oscam-emu/oscam-patched#5]
Configs are from Build: r11436

**Comment by oscam-emu** [comment]
I don't see any configs posted and we don't offer any configs or binaries...

Probably you are using a simple, non patched, oscam binary and you have an emu reader configured...

**Comment by limiteddi** [comment]
I built it from the trunk, its at the latest version

**Comment by oscam-emu** [comment]
Like I said, you are using a plain oscam source WITHOUT the emu patch. You have to patch your source with the oscam-emu.patch from https://github.com/oscam-emu/oscam-emu or just compile the already patched source from this repo. Or get a binary from somewhere else.
