### ISSUE TITLE
oscam-git11788@dd929d25 no more sound on PowerVU channels (test on 40.5W AMC) with Octagon SF8008

### ISSUE THREAD

**Issue by Suedschwede66** [oscam-emu/oscam-patched#50]
With oscam-git11788@dd929d25 no more sound on PowerVU channels (test on 40.5W AMC) with Octagon SF8008.
I had to change box type Dreambox to Sogno in oscam.conf, then it works again, that's definitely how it is but not what you want.

**Comment by nautilus7** [comment]
Ask the "gurus" that made this change in streamboard/gitlab. Sorry, I can't deal with those idiots devs anymore.

**Comment by ohmza** [comment]
@nautilus7 Yeah talked to @AbuBaniaz (a.k.a. oscamwala). He is one of the member of oscam-emu organization and the one who insisted to have that patch integrated on the trunk.

It seems that the genius dev like you couldn't even do such a basic things such as figuring out who is the actual owner of the patch or who insisted to have the patch integrated on the trunk.

**Comment by nautilus7** [comment]
fuck off you piece of shit.

**Comment by AbuBaniaz** [comment]
Let's be civil even though we disagree.

I requested that the sogno/unibox patch be added so that people who make softcams for ATV do not keep having to update the patch used.
