### ISSUE TITLE
Request a support for ABV CAS (CAID 4A67)

### ISSUE THREAD

**Issue by ohmza** [oscam-emu/oscam-patched#54]
Right now, oscam can only read the atr of the card. Oscam cannot read any other informations such as CAID. Also, ABV is not even on the list on oscam.version file.

Here is a log from oscam web interface:

2019/07/27 17:08:29 00000000 s     (main) creating pidfile /tmp/.oscam/oscam.pid with pid 5724
2019/07/27 17:08:29 00000000 s   (config) services reloaded: 0 services freed, 5 services loaded, rejected 0
2019/07/27 17:08:29 00000000 s   (config) userdb reloaded: 2 accounts loaded, 0 expired, 0 disabled
2019/07/27 17:08:29 00000000 s     (main) signal handling initialized
2019/07/27 17:08:29 00000000 s   (config) 147 service-id's loaded in 0 ms
2019/07/27 17:08:29 00000000 s      (net) newcamd: initialized (fd=3, port=12555)
2019/07/27 17:08:29 00000000 s      (net) -> CAID: 4A67 PROVID: 000000
2019/07/27 17:08:29 00000000 s      (net) cccam: initialized (fd=4, port=12544)
2019/07/27 17:08:29 00000000 s   (reader) CARD0 [mouse] creating thread for device /dev/ttyUSB8
2019/07/27 17:08:29 00000000 s     (stat) loadbalancer: could not open /tmp/.oscam/stat for reading (errno=2 No such file or directory)
2019/07/27 17:08:29 00000000 s     (main) waiting for local card init
2019/07/27 17:08:29 5D5A6B99 h    (webif) webif: decompressed 170217 bytes back into 405684 bytes
2019/07/27 17:08:29 5D5A6B99 h    (webif) HTTP Server running. ip=0.0.0.0 port=40016
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Buffers readed  0 bytes total time_us 76100
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 1 value 3b time_us 10589
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 2 value 7b time_us 10
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 3 value 11 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 4 value 00 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 5 value 00 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 6 value 41 time_us 5
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 7 value 42 time_us 5
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 8 value 56 time_us 14502
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 9 value 43 time_us 9
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 10 value 55 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 11 value 0c time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 12 value 02 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 13 value 05 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 14 value 02 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 15 value 90 time_us 5
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Flush readed byte Nr 16 value 00 time_us 6
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Buffers readed  16 bytes total time_us 100507
2019/07/27 17:08:29 2FB9567D r   (reader) CARD0 [mouse] Reader initialized (device=/dev/ttyUSB8, detect=cd, mhz=357, cardmhz=357)
2019/07/27 17:08:30 2FB9567D r   (reader) CARD0 [mouse] card detected
2019/07/27 17:08:30 2FB9567D r   (reader) CARD0 [mouse] Buffers readed  0 bytes total time_us 75110
2019/07/27 17:08:31 2FB9567D r   (reader) CARD0 [mouse] ATR: 3B 7B 11 00 00 41 42 56 43 55 0C 02 05 02 90 00 
2019/07/27 17:08:31 2FB9567D r   (reader) CARD0 [mouse] Init card protocol T0, FI=1, F=372, D=1, N=0
2019/07/27 17:08:31 2FB9567D r   (reader) CARD0 [mouse] Setting baudrate to 9600 bps
2019/07/27 17:08:31 2FB9567D r   (reader) CARD0 [mouse] Calculated work ETU is 104.20 us reader mhz = 357
2019/07/27 17:08:31 2FB9567D r   (reader) CARD0 [mouse] Buffers readed  0 bytes total time_us 75113
2019/07/27 17:08:31 2FB9567D r   (reader) CARD0 [mouse] ATR Fsmax is 5 MHz, clocking card to wanted user cardspeed off 3.57 MHz (specified in reader->mhz)
2019/07/27 17:08:32 2FB9567D r   (reader) CARD0 [mouse] card system not supported
2019/07/27 17:08:32 2FB9567D r   (reader) CARD0 [mouse] Normal mode failed, reverting to Deprecated Mode
2019/07/27 17:08:33 2FB9567D r   (reader) CARD0 [mouse] Buffers readed  0 bytes total time_us 75123
2019/07/27 17:08:34 2FB9567D r   (reader) CARD0 [mouse] ATR: 3B 7B 11 00 00 41 42 56 43 55 0C 02 05 02 90 00 
2019/07/27 17:08:34 2FB9567D r   (reader) CARD0 [mouse] Init card protocol T0, FI=1, F=372, D=1, N=0
2019/07/27 17:08:34 2FB9567D r   (reader) CARD0 [mouse] Calculated work ETU is 104.20 us reader mhz = 357
2019/07/27 17:08:34 2FB9567D r   (reader) CARD0 [mouse] Buffers readed  0 bytes total time_us 75104
2019/07/27 17:08:34 2FB9567D r   (reader) CARD0 [mouse] ATR Fsmax is 5 MHz, clocking card to wanted user cardspeed off 3.57 MHz (specified in reader->mhz)
2019/07/27 17:08:35 2FB9567D r   (reader) CARD0 [mouse] card system not supported
2019/07/27 17:08:35 2FB9567D r   (reader) CARD0 [mouse] THIS WAS A FAILED START ATTEMPT No 1 out of max alloted of 1
2019/07/27 17:08:35 2FB9567D r   (reader) CARD0 [mouse] card initializing error
2019/07/27 17:08:35 00000000 s     (main) init for all local cards done
2019/07/27 17:08:35 00000000 s (emmcache) loaded 0 emmcache records from /tmp/.oscam/oscam.emmcache in 0 ms
2019/07/27 17:08:35 00000000 s (emmcache) loaded 0 emmstat records from /tmp/.oscam/oscam.emmstat in 0 ms
2019/07/27 17:08:35 00000000 s (anticasc) anti cascading disabled

**Comment by oscam-emu** [comment]
Hi, I can't help with this, sorry. I am not familiar with this part of the
code. Please ask in the forum, or make a new ticket in the streamboard.
