### ISSUE TITLE
dvbcsa/dvbcsa.h

### ISSUE THREAD

**Issue by mr-unix01** [oscam-emu/oscam-patched#55]
HI,
I use debian 12 I have this problem
![Schermata del 2024-09-08 08-41-49](https://github.com/user-attachments/assets/f58933e6-bfa7-49bf-a670-100a2c4c6bb9)

**Comment by kalehrl** [comment]
You probably don't need dvbapi on a PC.

**Comment by mr-unix01** [comment]
yes solved thanks
