### ISSUE TITLE
BBC 27.5W with EMU doesn't work

### ISSUE THREAD

**Issue by Monello2** [oscam-emu/oscam-patched#57]
have done the following: I have entered the keys as follows in Softcam. key. 

**keys removed - do not post keys publicly** 

Then I entered the EMU reader in oscam. server as follows:
```
[reader]
label = emulator
protocol = emu
device = emulator
disablecrccws_only_for = 0E00:000000
caid = 0500,0604,090F,0E00,1010,1801,2600,2602,2610,4AE1
detect = cd
ident = 0500:000000,023800,021110,007400,007800;0604:000000;090F:000000;0E00:000000;1010:000000;1801:000000,007301,001101,002111;2600:000000;2602:000000;2610:000000;4AE1:000011,000014,0000FE
group = 1
emmcache = 2,1,2,1
emu_auproviders = 0604:010200;0E00:000000;1010:000000;2610:000000;4AE1:000011,000014,0000FE
emu_datecodedenabled = 0
```
 
 
and then copied the file softcam.key to etc/tuxbox/config
 
 
I also edited the lamedb file, entered all PIDs, stopped enigma with "init4", copied the lamedb to etc/engima and restarted enigma with "init3". 
 
Unfortunately, everything remains dark

**Comment by oscam-emu** [comment]
I can't tell if it's oscam-emu or enigma2 in fault. I need a log from oscam to see if it's actually asking for a key or not.

**Comment by Monello2** [comment]
---------------------------------------------------------
>> OSCam <<  cardserver log switched at Tue Aug  6 00:05:12 2019
-------------------------------------------------------------------------------
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [smartreader] Maturity level [F]=no age limit
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [smartreader] ready for requests
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [smartreader] found card system viaccess
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [viaccess] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max allotted of 1
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [viaccess] card detected
2019/08/06 00:05:12 00000000   >> OSCam << cardserver log switched, version build-DreamOSat-1.20_svn, build r11536-797 (arm-linux-gnueabihf-ssl-libusb)
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [viaccess] serial: ##########
2019/08/06 00:05:12 5C2F7A01 r   (reader) SRG-V6 [viaccess] provider: 1, id: ####################, sa: ########, geo: empty
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] provider: 2, id: ####################, sa: ########, geo: FF FF FF FF 
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/08/01 - 2019/09/15
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/06/27 - 2019/08/11
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/05/23 - 2019/07/07
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/04/18 - 2019/06/02
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/03/14 - 2019/04/28
2019/08/06 00:05:13 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/02/07 - 2019/03/24
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2019/01/03 - 2019/02/17
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2018/11/29 - 2019/01/13
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2018/10/25 - 2018/12/09
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2018/09/20 - 2018/11/04
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2018/08/26 - 2018/09/26
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 02, expiry date: 2018/08/26 - 2018/09/26
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 03, expiry date: 2018/08/26 - 2018/09/26
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 04, expiry date: 2018/08/26 - 2018/09/26
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 05, expiry date: 2018/08/26 - 2018/09/26
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [smartreader] ready for requests
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [smartreader] found card system nagra
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max allotted of 1
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] ROM:    D N A S P 1 8 0
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] REV:    M e r 0 0 0
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] SER:    ############
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] CAID:   1843
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] Prv.ID: 00 00 34 11 (sysid)
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] Prv.ID: 00 00 00 00 
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] class: 01, expiry date: 2018/08/16 - 2018/09/30
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] IRD ID: ############
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] active to: 2019/09/20 02:05
2019/08/06 00:05:14 5C2F7A01 r   (reader) SRG-V6 [viaccess] provider: 3, id: ######################, sa: ########, geo: FF FF FF FF 
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] -----------------------------------------
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] |id  |tier    |valid from  |valid to    |
2019/08/06 00:05:14 0DC0D959 r   (reader) HDplusHD02 [nagra] +----+--------+------------+------------+
2019/08/06 00:05:15 0DC0D959 r   (reader) HDplusHD02 [nagra] |8011|0066    |2012/04/26  |2013/04/27  |
2019/08/06 00:05:15 0DC0D959 r   (reader) HDplusHD02 [nagra] |8011|0067    |2010/01/19  |2010/01/20  |
2019/08/06 00:05:15 5C2F7A01 r   (reader) SRG-V6 [viaccess] provider: 4, id: ######################, sa: ########, geo: FF FF FF FF 
2019/08/06 00:05:15 0DC0D959 r   (reader) HDplusHD02 [nagra] |8011|0BEA    |2019/03/10  |2020/03/11  |
2019/08/06 00:05:15 0DC0D959 r   (reader) HDplusHD02 [nagra] -----------------------------------------
2019/08/06 00:05:15 5C2F7A01 r   (reader) SRG-V6 [viaccess] provider: 5, id: ######################, sa: ########, geo: FF FF FF FF 
2019/08/06 00:05:16 5C2F7A01 r   (reader) SRG-V6 [viaccess] provider: 6, id: ######################, sa: ########, geo: FF FF FF FF 
2019/08/06 00:05:17 00000000 s     (main) init for all local cards done
2019/08/06 00:05:17 00000000 s (emmcache) loaded 1335 emmcache records from /tmp/.oscam/oscam.emmcache in 14 ms
2019/08/06 00:05:17 00000000 s (emmcache) loaded 1335 emmstat records from /tmp/.oscam/oscam.emmstat in 11 ms
2019/08/06 00:05:17 00000000 s (anticasc) anti cascading disabled
2019/08/06 00:05:17 295B0451 c   (client) plain dvbapi-client granted (dvbapi, au=auto (7 reader))
2019/08/06 00:05:18 295B0451 c   (dvbapi) dvbapi channelcache loaded from /var/tuxbox/config/oscam.ccache
2019/08/06 00:05:18 295B0451 c   (dvbapi) Detected /dev/dvb/adapter0/demux0 Api: 0, userconfig boxtype: 1 maximum number of filters is 64 (oscam limit is 64)
2019/08/06 00:05:18 295B0451 c   (dvbapi) Detected /dev/dvb/adapter0/ca0 device, total available descramblers: 8
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0500 ECM_PID: 02ED PROVID: 060200 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0500 ECM_PID: 02E3 PROVID: 050800 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0500 ECM_PID: 02D9 PROVID: 040810 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 0 found 3 ECM pids and 8 STREAM pids in CA PMT
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 0 found channel in cache and matching prio -> start descrambling ecmpid 0 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 0500 PROVID 060200 ECMPID 02ED ANY CHID PMTPID 01F5 VPID 01F6
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 0 CAID: 1830 ECM_PID: 1CC2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 1 CAID: 1843 ECM_PID: 19C2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 2 CAID: 09C4 ECM_PID: 1BC2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 3 CAID: 098C ECM_PID: 1AC2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 4 CAID: 0648 ECM_PID: 1FC2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 5 CAID: 1860 ECM_PID: 1EC2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 6 CAID: 186A ECM_PID: 1DC2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 7 CAID: 0500 ECM_PID: 1DC3 PROVID: 051900 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 8 CAID: 098D ECM_PID: 18C2 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 9 CAID: 186D ECM_PID: 1D91 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 10 CAID: 06CB ECM_PID: 1BC3 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 11 CAID: 1842 ECM_PID: 1CC3 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 ecmpid 12 CAID: 4B64 ECM_PID: 1CC3 PROVID: 000000 
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 found 13 ECM pids and 5 STREAM pids in CA PMT
2019/08/06 00:05:18 295B0451 c   (dvbapi) Demuxer 1 trying to descramble PID 1 CAID 1843 PROVID 000000 ECMPID 19C2 ANY CHID PMTPID 0062 VPID 02FF
2019/08/06 00:05:18 295B0451 c      (ecm) dvbapi (0500@060200/08DE/4331/30:578851BA8ADE5497870375C4C40FD895): found (354 ms) by SRG-V6 - SRF 1 HD
2019/08/06 00:05:19 295B0451 c      (ecm) dvbapi (1843@000000/0000/5274/89:A19167F2104E26F482B8585B6AEC5B20): found (551 ms) by HDplusHD02 - WELT HD
2019/08/06 00:05:20 295B0451 c      (ecm) dvbapi (0500@060200/08DE/4331/30:2F5CEAC47180892B2EC31347B3449163): found (315 ms) by SRG-V6 - SRF 1 HD
2019/08/06 00:05:26 295B0451 c      (ecm) dvbapi (1843@000000/0000/5274/89:40666F21C42B93895DD9891A5535D041): found (545 ms) by HDplusHD02 - WELT HD
2019/08/06 00:05:30 295B0451 c      (ecm) dvbapi (0500@060200/08DE/4331/30:DB5201BE8B94B0A408063477939E5E64): found (319 ms) by SRG-V6 - SRF 1 HD
2019/08/06 00:05:40 295B0451 c      (ecm) dvbapi (0500@060200/08DE/4331/30:FB3E80652D4D491DA9B8D96DCBD2ED58): found (315 ms) by SRG-V6 - SRF 1 HD
2019/08/06 00:05:41 295B0451 c      (ecm) dvbapi (1843@000000/0000/5274/89:66A98C257184BDA2C97B3D11298C9DB5): found (538 ms) by HDplusHD02 - WELT HD
2019/08/06 00:05:50 295B0451 c      (ecm) dvbapi (0500@060200/08DE/4331/30:1A306791527435BE5A497FD392C617D3): found (316 ms) by SRG-V6 - SRF 1 HD

**Comment by oscam-emu** [comment]
What's this? This is not a log from a BBC channel...
