### ISSUE TITLE
PowerVU EMM algorithm updates ECM keys in wrong group

### ISSUE THREAD

**Issue by dodekana** [oscam-emu/oscam-patched#6]
Sony Group on Intelsat 20 and Intelsat 17 sometimes transmit emm data which has the same UA. For example, UA 00422FF6 which the emm key is valid for both. Although we already distinguish the Group ID, Oscam doesn't write the new ecm-key to the corresponding Group ID.

**Comment by oscam-emu** [comment]
See also the wiki: https://github.com/oscam-emu/oscam-patched/wiki/PowerVU-config#note-3
