### ISSUE TITLE
Gitlab sync seems not work properly 

### ISSUE THREAD

**Issue by WXbet** [oscam-emu/oscam-patched#6]
Hi @nautilus7,

seems this line https://github.com/oscam-emu/oscam-patched/blob/8a3c2de963ddaac690fec766919a14c5b566b500/.github/workflows/sync-gitlab.yml#L23 is not enought to to push all the changes to oscam-patched. This gets the tags only, not the changes itself.

**Comment by nautilus7** [comment]
Problem is in pull command. While `git fetch` gets the tags, `git pull` doesn't.  I am working on it.

**Comment by nautilus7** [comment]
Not exactly correct what I wrote earlier, but anyway, should be fixed with b39a134ea49f6760e26b05f6cc3d29a36a2b307c
