### ISSUE TITLE
sony,discovery on 68.5east not working on powervu any solution plz

### ISSUE THREAD

**Issue by colesbergkhn** [oscam-emu/oscam-patched#64]
hi,,, on 68.5east sony+discovery channels are not working any solution plz

**Comment by credoman** [comment]
Posted By Ghouri Today, 20:46 On Asiasat 7, Sony is autorolling again. Checked with Oscam Emu 11570.

**Comment by budiarno** [comment]
it uses ModeCW = 3 by now.

**Comment by budiarno** [comment]
> Posted By Ghouri Today, 20:46 On Asiasat 7, Sony is autorolling again. Checked with Oscam Emu 11570.

it uses ModeCW = 3

**Comment by credoman** [comment]
> > Posted By Ghouri Today, 20:46 On Asiasat 7, Sony is autorolling again. Checked with Oscam Emu 11570.
> 
> it uses ModeCW = 3 by now.

Sony network off
Asiasat.7 They changed to hashModeCw: 1,
modeCW: 8, modeCW: 35:modeCW: 25: & modeCW: 41 cyclic.

**Comment by nautilus7** [comment]
The solution is to send us the code to include it in oscam....
