### ISSUE TITLE
do you know 66e sony packets powervu enc.?

### ISSUE THREAD

**Issue by PAKO34** [oscam-emu/oscam-patched#68]
**do you know 66e sony packets powervu enc.?**

**Comment by credoman** [comment]
Posted By Ghouri Today, 20:46 On Asiasat 7, Sony is autorolling again. Checked with Oscam Emu 11570.

**Comment by credoman** [comment]
Sony network off
Asiasat.7 They changed to hashModeCw: 1,
modeCW: 8, modeCW: 35:modeCW: 25: & modeCW: 41 cyclic.

**Comment by NCODER85** [comment]
> Sony network off
> Asiasat.7 They changed to hashModeCw: 1,
> modeCW: 8, modeCW: 35:modeCW: 25: & modeCW: 41 cyclic.

Can it will be fix in coming oscam patch?

**Comment by budiarno** [comment]
> Can it will be fix in coming oscam patch? Also I am little confused as in oscam logs emu found valid CW. Screenshot attached.
> ![Screenshot_20191130-184254_Chrome](https://user-images.githubusercontent.com/56062267/69901032-99401e80-13a1-11ea-9453-847b1c6cd3a1.jpg)

That is because the ECM Key is valid, but the cw is actually not valid.

**Comment by NCODER85** [comment]
> > Can it will be fix in coming oscam patch? Also I am little confused as in oscam logs emu found valid CW. Screenshot attached.
> > ![Screenshot_20191130-184254_Chrome](https://user-images.githubusercontent.com/56062267/69901032-99401e80-13a1-11ea-9453-847b1c6cd3a1.jpg)
> 
> That is because the ECM Key is valid, but the cw is actually not valid.

Thanks for clarifying.
When can we expect this fix in oscam patch.

**Comment by Nabeelbutt786** [comment]
hello dear  help  me

**Comment by DRIVANnega** [comment]
i have theory, but its crazy to say this, i have been noticing a lot with how they did 2019 update on group category by channel hash code and it work great for not manual input our keys for every channel when it done automatic by group channel...to my point i making is, also we having problem with discovery channels entire globe with cycling same hash control word by this group modeCW: 8, modeCW: 35:modeCW: 25: & modeCW: 41 and cyclying every sec yes...here my theory, what if the EMM been working normally and ECM keys are correct but it doesn't know what to do with other modeCW in one group that requires to be in a group of CW into same ECM keys? not sure this work but this longshot in my theory if this helps

**Comment by nautilus7** [comment]
A fix can be expected when someone of you send us the code...
