### ISSUE TITLE
( Some)AC3 not decoded reasent oscam-patched

### ISSUE THREAD

**Issue by drgoody** [oscam-emu/oscam-patched#74]
Hello,

I'm receiving SES6 40W5. With C-Band and there's somthing strange.

ATM I use two different oscam Version to decode PowerVu channels.

a) old (oscam-emu (revision 11434) + oscam-svn) for the AC-3 Streams on Trp: 3723 R 30000
b) recent one for the modern Hash modes

On the recent version of oscam-patched it's not possible to decode AC-3 Streams from above mentioned trp.

I'm no devoloper, but this seams exactly the problem:
[http://www.streamboard.tv/oscam/changeset/11213](url)

I'm using vdr+ dvbapi

all the best

**Comment by oscam-emu** [comment]
Hi, the code from rev 11213 has been changed and is not valid anymore, so this cannot be the problem. I'll need logs from the troublesome channels with debug level 2 + 128 enabled. Make sure the log includes the moment you zap to the channel, so I can see the CA PMT parsing.
