### ISSUE TITLE
Support for Viaccess for  TNT France 19.2E

### ISSUE THREAD

**Issue by MOHAMED19OS** [oscam-emu/oscam-patched#79]
plesse adde Support for Viaccess for  TNT France 19.2E

**Comment by credoman** [comment]
Algorithm non published

**Comment by credoman** [comment]
published a library [https://mega.nz/file/arIlWQga#K79WMOk2Pzi4k3yF4QUtqfv1uHQSbt0wEUGmJT-bDXk](url)

**Comment by oscam-emu** [comment]
What I am supposed to do with these files? I can only find a oscam binary and some libssl, libcrypto, etc. libraries....
