### ISSUE TITLE
New EMM mask mode for PowerVU?

### ISSUE THREAD

**Issue by nicovil** [oscam-emu/oscam-patched#81]
Hello.

I'm not being able to open a trasponder using HashMode 32, which is already implemented. 

The problem seems to be that the EMM mask mode used by the provider is not actually supported by Oscam Emu.

Here is a real EMM example for an active customer (**005DDC77**) :

82309B1099010E000000068F005DDC77E05A03809650A8B0EEAE882DB1D92D7219A9EAE6B5B27716C975899276528096E2B5BD14EA8B79B54F1940E042097787D25F11153B5E60393B809601A56CBB4A28A9A432BD6F38DFCBB9C78FAD375378F50BA9D68096E11DE83733777391B5E1D3CB7D4241F85E650AA0BEF6775AAC8096E70F942D0929FFDB01316EF597BFA59251B67C36087DFDCDAEC789ABCBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

I did a debug with Oscam Emu code, and followed the unmask routine, where it's supposed that an unmasked EMM payload should be calculated, and then it will be unscrambled using the EMM key for this provider to retrieve the active ECM keys, but this EMM doesn't seems to be unmasked correctly (I didn't wanted to post the EMM key here).

Could this EMM mask mode be added to oscam emu?

**Comment by nautilus7** [comment]
If it's unmask mode 4, it was added recently. If not, feel free to send us the code ehen you find it.
