### ISSUE TITLE
decode setellite RSA key and box key 

### ISSUE THREAD

**Issue by naeem243** [oscam-emu/oscam-patched#84]
hello sir, i will make a oscam server for card sharing in oscam server so i have card of setellite card for 2 company but i m try more then my i is block plz can you help me decode RSA key and box key of setellite card same STB box becouse oscam server card ok but without RSA key and box key card block and how can decode card rsa key or box key from stb box same plz help me

**Comment by oscam-emu** [comment]
For card sharing questions, you have to ask in the streamboard forum.
