### ISSUE TITLE
PowerVU - Discovery 58W

### ISSUE THREAD

**Issue by bracarino** [oscam-emu/oscam-patched#91]
Hi,

All Discovery transponders (3840V, 3880V, 3960V) in 58W are not opening anymore. 
Keys are auto-rolling, but image is still scrambled.

`2022/07/17 20:15:29 0B030161 r      (emu) csaUsed: 0, xorMode: 0, ecmSrvid: 00E7, hashModeCw: 1, modeCW: 25`

**Comment by cbandcatcher** [comment]
Hi. Are there any boxes opening PowerVu+ for Discovery channels in 58 West c band?

**Comment by EnoSat** [comment]
some Chinese boxes should open it

**Comment by bracarino** [comment]
Guys, let's not confuse stuff.

There is no PowerVu+ (0e01) in 58W. All of them are PowerVu (0e00). However, some PowerVu transponders in 58W are using an updated PowerVu (0e00) that adds a nano 01 in ECM and are not supported by oscam as of today.

**Comment by cbandcatcher** [comment]
Thks for informing. However, are there any boxes supporting this updated
PowerVu?

**Comment by bracarino** [comment]
Yes

**Comment by cbandcatcher** [comment]
Thank you for your response. We hope it will be available soon on oscams or
simple softwares.

**Comment by nautilus7** [comment]
Feel free to send us the code to add...

**Comment by lorba7068** [comment]
if a developer does not have it

**Comment by cbandpowervu** [comment]
Hi all. There some news about opening Ten sports chs PowerVu in 75 east c band. Any confirmation about this?

**Comment by EnoSat** [comment]
try the chinese freesat forum
