### ISSUE TITLE
nano01 PowerVu - TV5

### ISSUE THREAD

**Issue by EnoSat** [oscam-emu/oscam-patched#95]
Has anyone modified the algo for nano 01 which is used for other TV5 channels to 1W?
00 81 30 3D 40 37 20 0E 00 **01** 00 00 A6 A0 00 ...

**Comment by EnoSat** [comment]
Still no one got info from commercials how to work with nano01 ?

**Comment by nautilus7** [comment]
No, feel free to send the code when you get it...
