### ISSUE TITLE
Oscam Emu and Biss channels

### ISSUE THREAD

**Issue by thejackal2017** [oscam-emu/oscam-patched#96]
I have a vps and i installed oscam emu and i have been looking for a way to run biss channels to cccam clients and i tried every possible solution ,but still no luck. The problem is When i select any biss channel on the stb i can't see any info in the user or from emu in the live log

I heard that biss channels don't send any ecm to the oscam emu  and oscam emu deals with such channels as FTA and the only way is to use oscam emu as client with dvbapi for this to work and in this case only oscam emu sends fake ecm  for biss channels . 

But for Receivers that don't support installing oscam emu as clients is such thing possible or is there any workaround for this  ? 

Regards

**Comment by cmhrky** [comment]
I am also having a problem with this issue. What do I need to do to use BISS via CCcam?

**Comment by nautilus7** [comment]
It might be the fact that BISS is using fake ECM with ECM pid 0x1FFF. Perhaps cccam drops this pid? I will have to look into the code.  

Did any recent change result in this problem? Can @cmhrky @thejackal2017 determine if this was always the case with cccam and BISS or if this problem introduced at some point?

oscam-svn vs oscam-emu should make any difference to this issue.

**Comment by nautilus7** [comment]
Probably cccam doesn't send any ecm. And this isn't really related to oscam-emu...
