### ISSUE TITLE
request powervu hash mode 44

### ISSUE THREAD

**Issue by skype1** [oscam-emu/oscam-patched#97]
dear sir,

please update powervu hash mode 44 asisasat 105east 4180 new powervu key  show blank screen and new hash mode 44...

needfull done it....thanks

**Comment by linuxstv** [comment]
Are you sure it's only about hash mode?

**Comment by skype1** [comment]
yes dear hash mode and table...

**Comment by nautilus7** [comment]
Feel free to send us the code...
