### ISSUE TITLE
No video 3720v 58w whit keys valid

### ISSUE THREAD

**Issue by lorba7068** [oscam-emu/oscam-patched#98]
A couple of days ago this problem has been occurring, the hashmode and cwmode have not changed, however there is no video... the keys are calculated by oscam emu correctly, because these same keys work and teams like GTmedia open the channels of this tp...3720v Sat: 058w but enigma equipment does not...

**Comment by arys123** [comment]
hello, the same problem on Telestar 12° west 11377v, auto roll emm keys are calculating the cw correct but no picture and audio. 
Can anyone fix this or help?

**Comment by lorba7068** [comment]
I am right now testing oscam 11424 r770 and I get this log cwmode: 182 ?
[oscam.log](https://github.com/oscam-emu/oscam-patched/files/10528492/oscam.log)

**Comment by televisivo** [comment]
> A couple of days ago this problem has been occurring, the hashmode and cwmode have not changed, however there is no video... the keys are calculated by oscam emu correctly, because these same keys work and teams like GTmedia open the channels of this tp...3720v Sat: 058w but enigma equipment does not...

GTmedia still opens this tp?

**Comment by lorba7068** [comment]
The channels and only some can be seen video, but not heard. The tp 3720 does not exist, I change to 3710

**Comment by televisivo** [comment]
> The channels and only some can be seen video, but not heard. The tp 3720 does not exist, I change to 3710

What version of Oscam are you using?

**Comment by nautilus7** [comment]
Feel free to send us any code to add...
